name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for RocNest!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Catalog / Inventory
        - Reservations / Bookings
        - Organizations / Members
        - Authentication
        - UI / UX
        - API
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any mockups, screenshots, or additional context.
